/** Human labels for audit-log event names. Unknown events fall back to a readable version of the raw name. */
const LABELS: Record<string, string> = {
  login_failed: "Failed sign-in",
  password_changed: "Password changed",
  password_reset: "Password reset",
  password_reset_requested: "Password reset requested",
  password_reset_failed: "Password reset failed",
  password_reset_otp_resent: "Reset code resent",
  password_reset_otp_verified: "Reset code verified",
  password_reset_totp_verified: "Reset verified with authenticator",
  password_reset_by_admin: "Password reset by admin",
  uid_changed: "User ID changed",
  uid_change_failed: "User ID change failed",
  uid_reset_by_admin: "User ID reset by admin",
  "2fa_enabled": "Two-factor enabled",
  "2fa_disabled": "Two-factor disabled",
  pin_set: "PIN set",
  pin_removed: "PIN removed",
  passkey_registered: "Passkey added",
  passkey_removed: "Passkey removed",
  security_questions_updated: "Security questions updated",
  security_question_verified: "Security question verified",
  security_question_failed: "Security question failed",
  force_logout_by_admin: "Signed out by admin",
  session_revoked_by_admin: "Session revoked by admin",
  user_updated: "Account updated",
  user_deleted: "Account deleted",
  user_created: "Account created",
  signup_requested: "New sign-up",
  entitlements_updated: "Entitlements updated",
  consent_recorded: "Consent recorded",
  announcement_created: "Announcement created",
  announcement_updated: "Announcement updated",
  announcement_published: "Announcement published",
  announcement_deleted: "Announcement deleted",
  automated_email_config_updated: "Email automation changed",
  automated_email_config_reset: "Email automation reset",
  automated_email_sent: "Automated email sent",
  automated_email_failed: "Automated email failed",
  automated_email_skipped: "Automated email skipped",
  email_template_override_updated: "Email template changed",
  email_template_override_restored: "Email template restored",
  email_template_published: "Email template published",
  email_template_reverted: "Email template version restored",
  email_template_test_sent: "Template test email sent",
  platform_settings_updated: "System settings changed",
  platform_backup_downloaded: "Backup downloaded",
  migration_reminder_sent: "Migration reminder sent",
  drive_connected: "Google Drive connected",
  drive_disconnected: "Google Drive disconnected",
  drive_data_restored: "Drive data restored",
  drive_account_change_resolved: "Drive account change resolved",
};

export const eventLabel = (e: string) => LABELS[e] ?? e.replace(/_/g, " ").replace(/^\w/, (c) => c.toUpperCase());
export const EVENT_OPTIONS = Object.entries(LABELS).map(([id, label]) => ({ id, label })).sort((a, b) => a.label.localeCompare(b.label));
/** Same rule the server uses for its severity filter. */
export const isHighSeverity = (e: string) => /failed|locked|suspend/i.test(e);
